java_binary(
    name = "task2",
    srcs = ["Main.java"],
    deps = ["//projects/data_analysis/common:java_common", "//third_party/maven/com/google/protobuf:protobuf_java"],
    main_class = "com.example.tasks.Task2",
    visibility = ["//projects/data_analysis:__pkg__"]
)
