package(default_visibility = ["//visibility:public"])

proto_library(
    name = "SMS_proto",
    srcs = ["SMS.proto"],
)

java_proto_library(
    name = "SMS_java_proto",
    deps = [":SMS_proto"],
)
