java_binary(
    name = "projects.opentrain.gtfs_pipeline.handle_data.DataHandler",
    srcs = ["DataHandler.java"],
    main_class = "DataHandler",
    visibility = ["//projects/opentrain/gtfs_pipeline:__pkg__"]
)