/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.hasadna.protobin_reader.ShareStoriesRequest', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.ShareStoriesResponse', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.Story', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.StoryItem', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.StoryList', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.ShareStoriesRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.ShareStoriesRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.ShareStoriesRequest.displayName = 'proto.com.hasadna.protobin_reader.ShareStoriesRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.ShareStoriesRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.ShareStoriesRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.ShareStoriesRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.ShareStoriesRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    stories: (f = msg.getStories()) && proto.com.hasadna.protobin_reader.StoryList.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.ShareStoriesRequest}
 */
proto.com.hasadna.protobin_reader.ShareStoriesRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.ShareStoriesRequest;
  return proto.com.hasadna.protobin_reader.ShareStoriesRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.ShareStoriesRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.ShareStoriesRequest}
 */
proto.com.hasadna.protobin_reader.ShareStoriesRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.hasadna.protobin_reader.StoryList;
      reader.readMessage(value,proto.com.hasadna.protobin_reader.StoryList.deserializeBinaryFromReader);
      msg.setStories(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.ShareStoriesRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.ShareStoriesRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.ShareStoriesRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.ShareStoriesRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStories();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.com.hasadna.protobin_reader.StoryList.serializeBinaryToWriter
    );
  }
};


/**
 * optional StoryList stories = 1;
 * @return {?proto.com.hasadna.protobin_reader.StoryList}
 */
proto.com.hasadna.protobin_reader.ShareStoriesRequest.prototype.getStories = function() {
  return /** @type{?proto.com.hasadna.protobin_reader.StoryList} */ (
    jspb.Message.getWrapperField(this, proto.com.hasadna.protobin_reader.StoryList, 1));
};


/** @param {?proto.com.hasadna.protobin_reader.StoryList|undefined} value */
proto.com.hasadna.protobin_reader.ShareStoriesRequest.prototype.setStories = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.com.hasadna.protobin_reader.ShareStoriesRequest.prototype.clearStories = function() {
  this.setStories(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.hasadna.protobin_reader.ShareStoriesRequest.prototype.hasStories = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.ShareStoriesResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.ShareStoriesResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.ShareStoriesResponse.displayName = 'proto.com.hasadna.protobin_reader.ShareStoriesResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.ShareStoriesResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.ShareStoriesResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.ShareStoriesResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.ShareStoriesResponse.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.ShareStoriesResponse}
 */
proto.com.hasadna.protobin_reader.ShareStoriesResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.ShareStoriesResponse;
  return proto.com.hasadna.protobin_reader.ShareStoriesResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.ShareStoriesResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.ShareStoriesResponse}
 */
proto.com.hasadna.protobin_reader.ShareStoriesResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.ShareStoriesResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.ShareStoriesResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.ShareStoriesResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.ShareStoriesResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.StoryItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.StoryItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.StoryItem.displayName = 'proto.com.hasadna.protobin_reader.StoryItem';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.StoryItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.StoryItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.StoryItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    timems: jspb.Message.getFieldWithDefault(msg, 1, 0),
    screenshot: msg.getScreenshot_asB64(),
    oneliner: jspb.Message.getFieldWithDefault(msg, 3, ""),
    note: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.StoryItem}
 */
proto.com.hasadna.protobin_reader.StoryItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.StoryItem;
  return proto.com.hasadna.protobin_reader.StoryItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.StoryItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.StoryItem}
 */
proto.com.hasadna.protobin_reader.StoryItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimems(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setScreenshot(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOneliner(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNote(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.StoryItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.StoryItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.StoryItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimems();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getScreenshot_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getOneliner();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNote();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional int64 timeMs = 1;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getTimems = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.StoryItem.prototype.setTimems = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bytes screenshot = 2;
 * @return {!(string|Uint8Array)}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getScreenshot = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes screenshot = 2;
 * This is a type-conversion wrapper around `getScreenshot()`
 * @return {string}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getScreenshot_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getScreenshot()));
};


/**
 * optional bytes screenshot = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getScreenshot()`
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getScreenshot_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getScreenshot()));
};


/** @param {!(string|Uint8Array)} value */
proto.com.hasadna.protobin_reader.StoryItem.prototype.setScreenshot = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional string oneliner = 3;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getOneliner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.StoryItem.prototype.setOneliner = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string note = 4;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getNote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.StoryItem.prototype.setNote = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.Story = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.hasadna.protobin_reader.Story.repeatedFields_, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.Story, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.Story.displayName = 'proto.com.hasadna.protobin_reader.Story';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.hasadna.protobin_reader.Story.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.Story.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.Story.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.Story} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.Story.toObject = function(includeInstance, msg) {
  var f, obj = {
    starttimems: jspb.Message.getFieldWithDefault(msg, 1, 0),
    endtimems: jspb.Message.getFieldWithDefault(msg, 2, 0),
    project: jspb.Message.getFieldWithDefault(msg, 3, ""),
    itemList: jspb.Message.toObjectList(msg.getItemList(),
    proto.com.hasadna.protobin_reader.StoryItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.Story}
 */
proto.com.hasadna.protobin_reader.Story.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.Story;
  return proto.com.hasadna.protobin_reader.Story.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.Story} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.Story}
 */
proto.com.hasadna.protobin_reader.Story.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStarttimems(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEndtimems(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setProject(value);
      break;
    case 4:
      var value = new proto.com.hasadna.protobin_reader.StoryItem;
      reader.readMessage(value,proto.com.hasadna.protobin_reader.StoryItem.deserializeBinaryFromReader);
      msg.addItem(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.Story.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.Story.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.Story} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.Story.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStarttimems();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getEndtimems();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getProject();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getItemList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.com.hasadna.protobin_reader.StoryItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 startTimeMs = 1;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.Story.prototype.getStarttimems = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.Story.prototype.setStarttimems = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 endTimeMs = 2;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.Story.prototype.getEndtimems = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.Story.prototype.setEndtimems = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string project = 3;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.Story.prototype.getProject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.Story.prototype.setProject = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated StoryItem item = 4;
 * @return {!Array<!proto.com.hasadna.protobin_reader.StoryItem>}
 */
proto.com.hasadna.protobin_reader.Story.prototype.getItemList = function() {
  return /** @type{!Array<!proto.com.hasadna.protobin_reader.StoryItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.hasadna.protobin_reader.StoryItem, 4));
};


/** @param {!Array<!proto.com.hasadna.protobin_reader.StoryItem>} value */
proto.com.hasadna.protobin_reader.Story.prototype.setItemList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.com.hasadna.protobin_reader.StoryItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.hasadna.protobin_reader.StoryItem}
 */
proto.com.hasadna.protobin_reader.Story.prototype.addItem = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.com.hasadna.protobin_reader.StoryItem, opt_index);
};


proto.com.hasadna.protobin_reader.Story.prototype.clearItemList = function() {
  this.setItemList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.StoryList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.hasadna.protobin_reader.StoryList.repeatedFields_, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.StoryList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.StoryList.displayName = 'proto.com.hasadna.protobin_reader.StoryList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.hasadna.protobin_reader.StoryList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.StoryList.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.StoryList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.StoryList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.StoryList.toObject = function(includeInstance, msg) {
  var f, obj = {
    storyList: jspb.Message.toObjectList(msg.getStoryList(),
    proto.com.hasadna.protobin_reader.Story.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.StoryList}
 */
proto.com.hasadna.protobin_reader.StoryList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.StoryList;
  return proto.com.hasadna.protobin_reader.StoryList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.StoryList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.StoryList}
 */
proto.com.hasadna.protobin_reader.StoryList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.hasadna.protobin_reader.Story;
      reader.readMessage(value,proto.com.hasadna.protobin_reader.Story.deserializeBinaryFromReader);
      msg.addStory(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.StoryList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.StoryList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.StoryList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.StoryList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStoryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.hasadna.protobin_reader.Story.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Story story = 1;
 * @return {!Array<!proto.com.hasadna.protobin_reader.Story>}
 */
proto.com.hasadna.protobin_reader.StoryList.prototype.getStoryList = function() {
  return /** @type{!Array<!proto.com.hasadna.protobin_reader.Story>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.hasadna.protobin_reader.Story, 1));
};


/** @param {!Array<!proto.com.hasadna.protobin_reader.Story>} value */
proto.com.hasadna.protobin_reader.StoryList.prototype.setStoryList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.hasadna.protobin_reader.Story=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.hasadna.protobin_reader.Story}
 */
proto.com.hasadna.protobin_reader.StoryList.prototype.addStory = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.hasadna.protobin_reader.Story, opt_index);
};


proto.com.hasadna.protobin_reader.StoryList.prototype.clearStoryList = function() {
  this.setStoryList([]);
};


goog.object.extend(exports, proto.com.hasadna.protobin_reader);
