/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.com.hasadna.protobin_reader.Config', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.Config.Frequency', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.FileData', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.FileData.Type', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.InvoiceCreator', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.InvoiceItem', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.InvoiceItemList', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.InvoiceReceiver', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.ScreenshotMetadata', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.StatusData', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.Story', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.StoryItem', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.StoryList', null, global);
goog.exportSymbol('proto.com.hasadna.protobin_reader.UiDefaults', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.Config = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.hasadna.protobin_reader.Config.repeatedFields_, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.Config, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.Config.displayName = 'proto.com.hasadna.protobin_reader.Config';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.hasadna.protobin_reader.Config.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.Config.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.Config.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.Config} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.Config.toObject = function(includeInstance, msg) {
  var f, obj = {
    screenshotFrequency: jspb.Message.getFieldWithDefault(msg, 1, 0),
    storiesPath: jspb.Message.getFieldWithDefault(msg, 2, ""),
    invoicesPath: jspb.Message.getFieldWithDefault(msg, 3, ""),
    invoiceCreator: (f = msg.getInvoiceCreator()) && proto.com.hasadna.protobin_reader.InvoiceCreator.toObject(includeInstance, f),
    invoiceReceiver: (f = msg.getInvoiceReceiver()) && proto.com.hasadna.protobin_reader.InvoiceReceiver.toObject(includeInstance, f),
    projectsList: jspb.Message.getRepeatedField(msg, 6)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.Config}
 */
proto.com.hasadna.protobin_reader.Config.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.Config;
  return proto.com.hasadna.protobin_reader.Config.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.Config} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.Config}
 */
proto.com.hasadna.protobin_reader.Config.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.hasadna.protobin_reader.Config.Frequency} */ (reader.readEnum());
      msg.setScreenshotFrequency(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStoriesPath(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setInvoicesPath(value);
      break;
    case 4:
      var value = new proto.com.hasadna.protobin_reader.InvoiceCreator;
      reader.readMessage(value,proto.com.hasadna.protobin_reader.InvoiceCreator.deserializeBinaryFromReader);
      msg.setInvoiceCreator(value);
      break;
    case 5:
      var value = new proto.com.hasadna.protobin_reader.InvoiceReceiver;
      reader.readMessage(value,proto.com.hasadna.protobin_reader.InvoiceReceiver.deserializeBinaryFromReader);
      msg.setInvoiceReceiver(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.addProjects(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.Config.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.Config.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.Config} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.Config.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getScreenshotFrequency();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getStoriesPath();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getInvoicesPath();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getInvoiceCreator();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      proto.com.hasadna.protobin_reader.InvoiceCreator.serializeBinaryToWriter
    );
  }
  f = message.getInvoiceReceiver();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.com.hasadna.protobin_reader.InvoiceReceiver.serializeBinaryToWriter
    );
  }
  f = message.getProjectsList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      6,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.com.hasadna.protobin_reader.Config.Frequency = {
  EVERY_10_MINUTES: 0,
  EVERY_15_MINUTES: 1,
  EVERY_20_MINUTES: 2
};

/**
 * optional Frequency screenshot_frequency = 1;
 * @return {!proto.com.hasadna.protobin_reader.Config.Frequency}
 */
proto.com.hasadna.protobin_reader.Config.prototype.getScreenshotFrequency = function() {
  return /** @type {!proto.com.hasadna.protobin_reader.Config.Frequency} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.com.hasadna.protobin_reader.Config.Frequency} value */
proto.com.hasadna.protobin_reader.Config.prototype.setScreenshotFrequency = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional string stories_path = 2;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.Config.prototype.getStoriesPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.Config.prototype.setStoriesPath = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string invoices_path = 3;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.Config.prototype.getInvoicesPath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.Config.prototype.setInvoicesPath = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional InvoiceCreator invoice_creator = 4;
 * @return {?proto.com.hasadna.protobin_reader.InvoiceCreator}
 */
proto.com.hasadna.protobin_reader.Config.prototype.getInvoiceCreator = function() {
  return /** @type{?proto.com.hasadna.protobin_reader.InvoiceCreator} */ (
    jspb.Message.getWrapperField(this, proto.com.hasadna.protobin_reader.InvoiceCreator, 4));
};


/** @param {?proto.com.hasadna.protobin_reader.InvoiceCreator|undefined} value */
proto.com.hasadna.protobin_reader.Config.prototype.setInvoiceCreator = function(value) {
  jspb.Message.setWrapperField(this, 4, value);
};


proto.com.hasadna.protobin_reader.Config.prototype.clearInvoiceCreator = function() {
  this.setInvoiceCreator(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.hasadna.protobin_reader.Config.prototype.hasInvoiceCreator = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional InvoiceReceiver invoice_receiver = 5;
 * @return {?proto.com.hasadna.protobin_reader.InvoiceReceiver}
 */
proto.com.hasadna.protobin_reader.Config.prototype.getInvoiceReceiver = function() {
  return /** @type{?proto.com.hasadna.protobin_reader.InvoiceReceiver} */ (
    jspb.Message.getWrapperField(this, proto.com.hasadna.protobin_reader.InvoiceReceiver, 5));
};


/** @param {?proto.com.hasadna.protobin_reader.InvoiceReceiver|undefined} value */
proto.com.hasadna.protobin_reader.Config.prototype.setInvoiceReceiver = function(value) {
  jspb.Message.setWrapperField(this, 5, value);
};


proto.com.hasadna.protobin_reader.Config.prototype.clearInvoiceReceiver = function() {
  this.setInvoiceReceiver(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.hasadna.protobin_reader.Config.prototype.hasInvoiceReceiver = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * repeated string projects = 6;
 * @return {!Array<string>}
 */
proto.com.hasadna.protobin_reader.Config.prototype.getProjectsList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 6));
};


/** @param {!Array<string>} value */
proto.com.hasadna.protobin_reader.Config.prototype.setProjectsList = function(value) {
  jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.com.hasadna.protobin_reader.Config.prototype.addProjects = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


proto.com.hasadna.protobin_reader.Config.prototype.clearProjectsList = function() {
  this.setProjectsList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.UiDefaults = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.hasadna.protobin_reader.UiDefaults.repeatedFields_, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.UiDefaults, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.UiDefaults.displayName = 'proto.com.hasadna.protobin_reader.UiDefaults';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.hasadna.protobin_reader.UiDefaults.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.UiDefaults.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.UiDefaults.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.UiDefaults} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.UiDefaults.toObject = function(includeInstance, msg) {
  var f, obj = {
    projectList: jspb.Message.getRepeatedField(msg, 1),
    left: jspb.Message.getFieldWithDefault(msg, 2, 0),
    top: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.UiDefaults}
 */
proto.com.hasadna.protobin_reader.UiDefaults.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.UiDefaults;
  return proto.com.hasadna.protobin_reader.UiDefaults.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.UiDefaults} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.UiDefaults}
 */
proto.com.hasadna.protobin_reader.UiDefaults.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.addProject(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLeft(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTop(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.UiDefaults.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.UiDefaults.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.UiDefaults} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.UiDefaults.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProjectList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      1,
      f
    );
  }
  f = message.getLeft();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getTop();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * repeated string project = 1;
 * @return {!Array<string>}
 */
proto.com.hasadna.protobin_reader.UiDefaults.prototype.getProjectList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 1));
};


/** @param {!Array<string>} value */
proto.com.hasadna.protobin_reader.UiDefaults.prototype.setProjectList = function(value) {
  jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {!string} value
 * @param {number=} opt_index
 */
proto.com.hasadna.protobin_reader.UiDefaults.prototype.addProject = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


proto.com.hasadna.protobin_reader.UiDefaults.prototype.clearProjectList = function() {
  this.setProjectList([]);
};


/**
 * optional int32 left = 2;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.UiDefaults.prototype.getLeft = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.UiDefaults.prototype.setLeft = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 top = 3;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.UiDefaults.prototype.getTop = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.UiDefaults.prototype.setTop = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.StatusData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.StatusData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.StatusData.displayName = 'proto.com.hasadna.protobin_reader.StatusData';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.StatusData.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.StatusData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.StatusData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.StatusData.toObject = function(includeInstance, msg) {
  var f, obj = {
    project: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.StatusData}
 */
proto.com.hasadna.protobin_reader.StatusData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.StatusData;
  return proto.com.hasadna.protobin_reader.StatusData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.StatusData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.StatusData}
 */
proto.com.hasadna.protobin_reader.StatusData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProject(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.StatusData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.StatusData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.StatusData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.StatusData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProject();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string project = 1;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.StatusData.prototype.getProject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.StatusData.prototype.setProject = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.ScreenshotMetadata = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.ScreenshotMetadata, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.ScreenshotMetadata.displayName = 'proto.com.hasadna.protobin_reader.ScreenshotMetadata';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.ScreenshotMetadata.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.ScreenshotMetadata.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.ScreenshotMetadata} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.ScreenshotMetadata.toObject = function(includeInstance, msg) {
  var f, obj = {
    project: jspb.Message.getFieldWithDefault(msg, 1, ""),
    oneliner: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.ScreenshotMetadata}
 */
proto.com.hasadna.protobin_reader.ScreenshotMetadata.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.ScreenshotMetadata;
  return proto.com.hasadna.protobin_reader.ScreenshotMetadata.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.ScreenshotMetadata} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.ScreenshotMetadata}
 */
proto.com.hasadna.protobin_reader.ScreenshotMetadata.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProject(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setOneliner(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.ScreenshotMetadata.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.ScreenshotMetadata.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.ScreenshotMetadata} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.ScreenshotMetadata.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProject();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getOneliner();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string project = 1;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.ScreenshotMetadata.prototype.getProject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.ScreenshotMetadata.prototype.setProject = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string oneliner = 2;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.ScreenshotMetadata.prototype.getOneliner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.ScreenshotMetadata.prototype.setOneliner = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.FileData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.com.hasadna.protobin_reader.FileData.oneofGroups_);
};
goog.inherits(proto.com.hasadna.protobin_reader.FileData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.FileData.displayName = 'proto.com.hasadna.protobin_reader.FileData';
}
/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.com.hasadna.protobin_reader.FileData.oneofGroups_ = [[4,5,6]];

/**
 * @enum {number}
 */
proto.com.hasadna.protobin_reader.FileData.OneofContentCase = {
  ONEOF_CONTENT_NOT_SET: 0,
  IMAGE_BYTES: 4,
  SCREENSHOT_METADATA: 5,
  STATUS_DATA: 6
};

/**
 * @return {proto.com.hasadna.protobin_reader.FileData.OneofContentCase}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.getOneofContentCase = function() {
  return /** @type {proto.com.hasadna.protobin_reader.FileData.OneofContentCase} */(jspb.Message.computeOneofCase(this, proto.com.hasadna.protobin_reader.FileData.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.FileData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.FileData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.FileData.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    timems: jspb.Message.getFieldWithDefault(msg, 2, 0),
    filename: jspb.Message.getFieldWithDefault(msg, 3, ""),
    imageBytes: msg.getImageBytes_asB64(),
    screenshotMetadata: (f = msg.getScreenshotMetadata()) && proto.com.hasadna.protobin_reader.ScreenshotMetadata.toObject(includeInstance, f),
    statusData: (f = msg.getStatusData()) && proto.com.hasadna.protobin_reader.StatusData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.FileData}
 */
proto.com.hasadna.protobin_reader.FileData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.FileData;
  return proto.com.hasadna.protobin_reader.FileData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.FileData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.FileData}
 */
proto.com.hasadna.protobin_reader.FileData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.com.hasadna.protobin_reader.FileData.Type} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimems(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilename(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setImageBytes(value);
      break;
    case 5:
      var value = new proto.com.hasadna.protobin_reader.ScreenshotMetadata;
      reader.readMessage(value,proto.com.hasadna.protobin_reader.ScreenshotMetadata.deserializeBinaryFromReader);
      msg.setScreenshotMetadata(value);
      break;
    case 6:
      var value = new proto.com.hasadna.protobin_reader.StatusData;
      reader.readMessage(value,proto.com.hasadna.protobin_reader.StatusData.deserializeBinaryFromReader);
      msg.setStatusData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.FileData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.FileData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.FileData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getTimems();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getFilename();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBytes(
      4,
      f
    );
  }
  f = message.getScreenshotMetadata();
  if (f != null) {
    writer.writeMessage(
      5,
      f,
      proto.com.hasadna.protobin_reader.ScreenshotMetadata.serializeBinaryToWriter
    );
  }
  f = message.getStatusData();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      proto.com.hasadna.protobin_reader.StatusData.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.com.hasadna.protobin_reader.FileData.Type = {
  UNKNOWN: 0,
  START: 1,
  RUNNING: 2,
  SCREENSHOT: 3,
  SCREENSHOT_METADATA: 4,
  END: 5
};

/**
 * optional Type type = 1;
 * @return {!proto.com.hasadna.protobin_reader.FileData.Type}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.getType = function() {
  return /** @type {!proto.com.hasadna.protobin_reader.FileData.Type} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {!proto.com.hasadna.protobin_reader.FileData.Type} value */
proto.com.hasadna.protobin_reader.FileData.prototype.setType = function(value) {
  jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional int64 timeMs = 2;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.getTimems = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.FileData.prototype.setTimems = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string filename = 3;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.getFilename = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.FileData.prototype.setFilename = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional bytes image_bytes = 4;
 * @return {!(string|Uint8Array)}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.getImageBytes = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * optional bytes image_bytes = 4;
 * This is a type-conversion wrapper around `getImageBytes()`
 * @return {string}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.getImageBytes_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getImageBytes()));
};


/**
 * optional bytes image_bytes = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getImageBytes()`
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.getImageBytes_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getImageBytes()));
};


/** @param {!(string|Uint8Array)} value */
proto.com.hasadna.protobin_reader.FileData.prototype.setImageBytes = function(value) {
  jspb.Message.setOneofField(this, 4, proto.com.hasadna.protobin_reader.FileData.oneofGroups_[0], value);
};


proto.com.hasadna.protobin_reader.FileData.prototype.clearImageBytes = function() {
  jspb.Message.setOneofField(this, 4, proto.com.hasadna.protobin_reader.FileData.oneofGroups_[0], undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.hasImageBytes = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ScreenshotMetadata screenshot_metadata = 5;
 * @return {?proto.com.hasadna.protobin_reader.ScreenshotMetadata}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.getScreenshotMetadata = function() {
  return /** @type{?proto.com.hasadna.protobin_reader.ScreenshotMetadata} */ (
    jspb.Message.getWrapperField(this, proto.com.hasadna.protobin_reader.ScreenshotMetadata, 5));
};


/** @param {?proto.com.hasadna.protobin_reader.ScreenshotMetadata|undefined} value */
proto.com.hasadna.protobin_reader.FileData.prototype.setScreenshotMetadata = function(value) {
  jspb.Message.setOneofWrapperField(this, 5, proto.com.hasadna.protobin_reader.FileData.oneofGroups_[0], value);
};


proto.com.hasadna.protobin_reader.FileData.prototype.clearScreenshotMetadata = function() {
  this.setScreenshotMetadata(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.hasScreenshotMetadata = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * optional StatusData status_data = 6;
 * @return {?proto.com.hasadna.protobin_reader.StatusData}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.getStatusData = function() {
  return /** @type{?proto.com.hasadna.protobin_reader.StatusData} */ (
    jspb.Message.getWrapperField(this, proto.com.hasadna.protobin_reader.StatusData, 6));
};


/** @param {?proto.com.hasadna.protobin_reader.StatusData|undefined} value */
proto.com.hasadna.protobin_reader.FileData.prototype.setStatusData = function(value) {
  jspb.Message.setOneofWrapperField(this, 6, proto.com.hasadna.protobin_reader.FileData.oneofGroups_[0], value);
};


proto.com.hasadna.protobin_reader.FileData.prototype.clearStatusData = function() {
  this.setStatusData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.com.hasadna.protobin_reader.FileData.prototype.hasStatusData = function() {
  return jspb.Message.getField(this, 6) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.StoryItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.StoryItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.StoryItem.displayName = 'proto.com.hasadna.protobin_reader.StoryItem';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.StoryItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.StoryItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.StoryItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    timems: jspb.Message.getFieldWithDefault(msg, 1, 0),
    screenshot: msg.getScreenshot_asB64(),
    oneliner: jspb.Message.getFieldWithDefault(msg, 3, ""),
    note: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.StoryItem}
 */
proto.com.hasadna.protobin_reader.StoryItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.StoryItem;
  return proto.com.hasadna.protobin_reader.StoryItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.StoryItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.StoryItem}
 */
proto.com.hasadna.protobin_reader.StoryItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimems(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setScreenshot(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setOneliner(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setNote(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.StoryItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.StoryItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.StoryItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTimems();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getScreenshot_asU8();
  if (f.length > 0) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = message.getOneliner();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getNote();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional int64 timeMs = 1;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getTimems = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.StoryItem.prototype.setTimems = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional bytes screenshot = 2;
 * @return {!(string|Uint8Array)}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getScreenshot = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * optional bytes screenshot = 2;
 * This is a type-conversion wrapper around `getScreenshot()`
 * @return {string}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getScreenshot_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getScreenshot()));
};


/**
 * optional bytes screenshot = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getScreenshot()`
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getScreenshot_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getScreenshot()));
};


/** @param {!(string|Uint8Array)} value */
proto.com.hasadna.protobin_reader.StoryItem.prototype.setScreenshot = function(value) {
  jspb.Message.setProto3BytesField(this, 2, value);
};


/**
 * optional string oneliner = 3;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getOneliner = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.StoryItem.prototype.setOneliner = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string note = 4;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.StoryItem.prototype.getNote = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.StoryItem.prototype.setNote = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.Story = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.hasadna.protobin_reader.Story.repeatedFields_, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.Story, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.Story.displayName = 'proto.com.hasadna.protobin_reader.Story';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.hasadna.protobin_reader.Story.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.Story.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.Story.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.Story} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.Story.toObject = function(includeInstance, msg) {
  var f, obj = {
    starttimems: jspb.Message.getFieldWithDefault(msg, 1, 0),
    endtimems: jspb.Message.getFieldWithDefault(msg, 2, 0),
    project: jspb.Message.getFieldWithDefault(msg, 3, ""),
    itemList: jspb.Message.toObjectList(msg.getItemList(),
    proto.com.hasadna.protobin_reader.StoryItem.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.Story}
 */
proto.com.hasadna.protobin_reader.Story.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.Story;
  return proto.com.hasadna.protobin_reader.Story.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.Story} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.Story}
 */
proto.com.hasadna.protobin_reader.Story.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStarttimems(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEndtimems(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setProject(value);
      break;
    case 4:
      var value = new proto.com.hasadna.protobin_reader.StoryItem;
      reader.readMessage(value,proto.com.hasadna.protobin_reader.StoryItem.deserializeBinaryFromReader);
      msg.addItem(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.Story.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.Story.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.Story} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.Story.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStarttimems();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getEndtimems();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getProject();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getItemList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.com.hasadna.protobin_reader.StoryItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 startTimeMs = 1;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.Story.prototype.getStarttimems = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.Story.prototype.setStarttimems = function(value) {
  jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * optional int64 endTimeMs = 2;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.Story.prototype.getEndtimems = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.Story.prototype.setEndtimems = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string project = 3;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.Story.prototype.getProject = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.Story.prototype.setProject = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated StoryItem item = 4;
 * @return {!Array<!proto.com.hasadna.protobin_reader.StoryItem>}
 */
proto.com.hasadna.protobin_reader.Story.prototype.getItemList = function() {
  return /** @type{!Array<!proto.com.hasadna.protobin_reader.StoryItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.hasadna.protobin_reader.StoryItem, 4));
};


/** @param {!Array<!proto.com.hasadna.protobin_reader.StoryItem>} value */
proto.com.hasadna.protobin_reader.Story.prototype.setItemList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.com.hasadna.protobin_reader.StoryItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.hasadna.protobin_reader.StoryItem}
 */
proto.com.hasadna.protobin_reader.Story.prototype.addItem = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.com.hasadna.protobin_reader.StoryItem, opt_index);
};


proto.com.hasadna.protobin_reader.Story.prototype.clearItemList = function() {
  this.setItemList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.StoryList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.hasadna.protobin_reader.StoryList.repeatedFields_, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.StoryList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.StoryList.displayName = 'proto.com.hasadna.protobin_reader.StoryList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.hasadna.protobin_reader.StoryList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.StoryList.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.StoryList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.StoryList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.StoryList.toObject = function(includeInstance, msg) {
  var f, obj = {
    storyList: jspb.Message.toObjectList(msg.getStoryList(),
    proto.com.hasadna.protobin_reader.Story.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.StoryList}
 */
proto.com.hasadna.protobin_reader.StoryList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.StoryList;
  return proto.com.hasadna.protobin_reader.StoryList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.StoryList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.StoryList}
 */
proto.com.hasadna.protobin_reader.StoryList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.hasadna.protobin_reader.Story;
      reader.readMessage(value,proto.com.hasadna.protobin_reader.Story.deserializeBinaryFromReader);
      msg.addStory(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.StoryList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.StoryList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.StoryList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.StoryList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStoryList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.hasadna.protobin_reader.Story.serializeBinaryToWriter
    );
  }
};


/**
 * repeated Story story = 1;
 * @return {!Array<!proto.com.hasadna.protobin_reader.Story>}
 */
proto.com.hasadna.protobin_reader.StoryList.prototype.getStoryList = function() {
  return /** @type{!Array<!proto.com.hasadna.protobin_reader.Story>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.hasadna.protobin_reader.Story, 1));
};


/** @param {!Array<!proto.com.hasadna.protobin_reader.Story>} value */
proto.com.hasadna.protobin_reader.StoryList.prototype.setStoryList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.hasadna.protobin_reader.Story=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.hasadna.protobin_reader.Story}
 */
proto.com.hasadna.protobin_reader.StoryList.prototype.addStory = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.hasadna.protobin_reader.Story, opt_index);
};


proto.com.hasadna.protobin_reader.StoryList.prototype.clearStoryList = function() {
  this.setStoryList([]);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.InvoiceItem = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.InvoiceItem, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.InvoiceItem.displayName = 'proto.com.hasadna.protobin_reader.InvoiceItem';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.InvoiceItem.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.InvoiceItem} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.InvoiceItem.toObject = function(includeInstance, msg) {
  var f, obj = {
    title: jspb.Message.getFieldWithDefault(msg, 1, ""),
    description: jspb.Message.getFieldWithDefault(msg, 2, ""),
    timeWorkedMs: jspb.Message.getFieldWithDefault(msg, 3, 0),
    hourlyRate: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    dollaramount: +jspb.Message.getFieldWithDefault(msg, 5, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.InvoiceItem}
 */
proto.com.hasadna.protobin_reader.InvoiceItem.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.InvoiceItem;
  return proto.com.hasadna.protobin_reader.InvoiceItem.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.InvoiceItem} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.InvoiceItem}
 */
proto.com.hasadna.protobin_reader.InvoiceItem.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimeWorkedMs(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setHourlyRate(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setDollaramount(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.InvoiceItem.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.InvoiceItem} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.InvoiceItem.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getTimeWorkedMs();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getHourlyRate();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getDollaramount();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
};


/**
 * optional string title = 1;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.setTitle = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string description = 2;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional int64 time_worked_ms = 3;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.getTimeWorkedMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.setTimeWorkedMs = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional double hourly_rate = 4;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.getHourlyRate = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.setHourlyRate = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double dollarAmount = 5;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.getDollaramount = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.InvoiceItem.prototype.setDollaramount = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.InvoiceItemList = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.com.hasadna.protobin_reader.InvoiceItemList.repeatedFields_, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.InvoiceItemList, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.InvoiceItemList.displayName = 'proto.com.hasadna.protobin_reader.InvoiceItemList';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.InvoiceItemList.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.InvoiceItemList} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.toObject = function(includeInstance, msg) {
  var f, obj = {
    itemList: jspb.Message.toObjectList(msg.getItemList(),
    proto.com.hasadna.protobin_reader.InvoiceItem.toObject, includeInstance),
    starttimems: jspb.Message.getFieldWithDefault(msg, 2, 0),
    endtimems: jspb.Message.getFieldWithDefault(msg, 3, 0),
    subtotal: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    total: +jspb.Message.getFieldWithDefault(msg, 5, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.InvoiceItemList}
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.InvoiceItemList;
  return proto.com.hasadna.protobin_reader.InvoiceItemList.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.InvoiceItemList} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.InvoiceItemList}
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.com.hasadna.protobin_reader.InvoiceItem;
      reader.readMessage(value,proto.com.hasadna.protobin_reader.InvoiceItem.deserializeBinaryFromReader);
      msg.addItem(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setStarttimems(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setEndtimems(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setSubtotal(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTotal(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.InvoiceItemList.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.InvoiceItemList} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getItemList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.com.hasadna.protobin_reader.InvoiceItem.serializeBinaryToWriter
    );
  }
  f = message.getStarttimems();
  if (f !== 0) {
    writer.writeInt64(
      2,
      f
    );
  }
  f = message.getEndtimems();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getSubtotal();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getTotal();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
};


/**
 * repeated InvoiceItem item = 1;
 * @return {!Array<!proto.com.hasadna.protobin_reader.InvoiceItem>}
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.getItemList = function() {
  return /** @type{!Array<!proto.com.hasadna.protobin_reader.InvoiceItem>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.com.hasadna.protobin_reader.InvoiceItem, 1));
};


/** @param {!Array<!proto.com.hasadna.protobin_reader.InvoiceItem>} value */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.setItemList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.com.hasadna.protobin_reader.InvoiceItem=} opt_value
 * @param {number=} opt_index
 * @return {!proto.com.hasadna.protobin_reader.InvoiceItem}
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.addItem = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.com.hasadna.protobin_reader.InvoiceItem, opt_index);
};


proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.clearItemList = function() {
  this.setItemList([]);
};


/**
 * optional int64 startTimeMs = 2;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.getStarttimems = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.setStarttimems = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 endTimeMs = 3;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.getEndtimems = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.setEndtimems = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional double subtotal = 4;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.getSubtotal = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.setSubtotal = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double total = 5;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.getTotal = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.InvoiceItemList.prototype.setTotal = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.InvoiceCreator = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.InvoiceCreator, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.InvoiceCreator.displayName = 'proto.com.hasadna.protobin_reader.InvoiceCreator';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.InvoiceCreator.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.InvoiceCreator} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    phoneNumber: jspb.Message.getFieldWithDefault(msg, 2, ""),
    email: jspb.Message.getFieldWithDefault(msg, 3, ""),
    website: jspb.Message.getFieldWithDefault(msg, 4, ""),
    streetAndNumber: jspb.Message.getFieldWithDefault(msg, 5, ""),
    cityStateCountry: jspb.Message.getFieldWithDefault(msg, 6, ""),
    zipCode: jspb.Message.getFieldWithDefault(msg, 7, ""),
    tagline: jspb.Message.getFieldWithDefault(msg, 8, ""),
    hourlyRateUsd: +jspb.Message.getFieldWithDefault(msg, 9, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.InvoiceCreator}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.InvoiceCreator;
  return proto.com.hasadna.protobin_reader.InvoiceCreator.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.InvoiceCreator} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.InvoiceCreator}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPhoneNumber(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setEmail(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setWebsite(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setStreetAndNumber(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setCityStateCountry(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setZipCode(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setTagline(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setHourlyRateUsd(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.InvoiceCreator.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.InvoiceCreator} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPhoneNumber();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getEmail();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getWebsite();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
  f = message.getStreetAndNumber();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getCityStateCountry();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getZipCode();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getTagline();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
  f = message.getHourlyRateUsd();
  if (f !== 0.0) {
    writer.writeDouble(
      9,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string phone_number = 2;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.getPhoneNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.setPhoneNumber = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string email = 3;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.getEmail = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.setEmail = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string website = 4;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.getWebsite = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.setWebsite = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string street_and_number = 5;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.getStreetAndNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.setStreetAndNumber = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string city_state_country = 6;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.getCityStateCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.setCityStateCountry = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string zip_code = 7;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.getZipCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.setZipCode = function(value) {
  jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * optional string tagline = 8;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.getTagline = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.setTagline = function(value) {
  jspb.Message.setProto3StringField(this, 8, value);
};


/**
 * optional double hourly_rate_usd = 9;
 * @return {number}
 */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.getHourlyRateUsd = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 9, 0.0));
};


/** @param {number} value */
proto.com.hasadna.protobin_reader.InvoiceCreator.prototype.setHourlyRateUsd = function(value) {
  jspb.Message.setProto3FloatField(this, 9, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.com.hasadna.protobin_reader.InvoiceReceiver = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.com.hasadna.protobin_reader.InvoiceReceiver, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.com.hasadna.protobin_reader.InvoiceReceiver.displayName = 'proto.com.hasadna.protobin_reader.InvoiceReceiver';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.com.hasadna.protobin_reader.InvoiceReceiver.prototype.toObject = function(opt_includeInstance) {
  return proto.com.hasadna.protobin_reader.InvoiceReceiver.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.com.hasadna.protobin_reader.InvoiceReceiver} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.InvoiceReceiver.toObject = function(includeInstance, msg) {
  var f, obj = {
    name: jspb.Message.getFieldWithDefault(msg, 1, ""),
    streetAndNumber: jspb.Message.getFieldWithDefault(msg, 2, ""),
    cityStateCountry: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.com.hasadna.protobin_reader.InvoiceReceiver}
 */
proto.com.hasadna.protobin_reader.InvoiceReceiver.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.com.hasadna.protobin_reader.InvoiceReceiver;
  return proto.com.hasadna.protobin_reader.InvoiceReceiver.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.com.hasadna.protobin_reader.InvoiceReceiver} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.com.hasadna.protobin_reader.InvoiceReceiver}
 */
proto.com.hasadna.protobin_reader.InvoiceReceiver.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setStreetAndNumber(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setCityStateCountry(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.com.hasadna.protobin_reader.InvoiceReceiver.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.com.hasadna.protobin_reader.InvoiceReceiver.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.com.hasadna.protobin_reader.InvoiceReceiver} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.com.hasadna.protobin_reader.InvoiceReceiver.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getStreetAndNumber();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getCityStateCountry();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string name = 1;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceReceiver.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceReceiver.prototype.setName = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string street_and_number = 2;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceReceiver.prototype.getStreetAndNumber = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceReceiver.prototype.setStreetAndNumber = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string city_state_country = 3;
 * @return {string}
 */
proto.com.hasadna.protobin_reader.InvoiceReceiver.prototype.getCityStateCountry = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.com.hasadna.protobin_reader.InvoiceReceiver.prototype.setCityStateCountry = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


goog.object.extend(exports, proto.com.hasadna.protobin_reader);
