proto_library(
    name = "agency_proto",
    srcs = ["agency.proto"]
)

java_proto_library(
    name = "agency_java_proto",
    deps = [":agency_proto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "calendar_proto",
    srcs = ["calendar.proto"]
)

java_proto_library(
    name = "calendar_java_proto",
    deps = [":calendar_proto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "fare_attributes_proto",
    srcs = ["fare_attributes.proto"]
)

java_proto_library(
    name = "fare_attributes_java_proto",
    deps = [":fare_attributes_proto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "fare_rules_proto",
    srcs = ["fare_rules.proto"]
)

java_proto_library(
    name = "fare_rules_java_proto",
    deps = [":fare_rules_proto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "routes_proto",
    srcs = ["routes.proto"]
)

java_proto_library(
    name = "routes_java_proto",
    deps = [":routes_proto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "shapes_proto",
    srcs = ["shapes.proto"]
)

java_proto_library(
    name = "shapes_java_proto",
    deps = [":shapes_proto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "stop_time_proto",
    srcs = ["stop_times.proto"]
)

java_proto_library(
    name = "stop_time_java_proto",
    deps = [":stop_time_proto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "stops_proto",
    srcs = ["stops.proto"]
)

java_proto_library(
    name = "stops_java_proto",
    deps = [":stops_proto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "translations_proto",
    srcs = ["translations.proto"]
)

java_proto_library(
    name = "translations_java_proto",
    deps = [":translations_proto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "trips_proto",
    srcs = ["trips.proto"]
)

java_proto_library(
    name = "trips_java_proto",
    deps = [":trips_proto"],
    visibility = ["//visibility:public"]
)