proto_library(
    name = "common_proto",
    srcs = ["common.proto"]
)

java_proto_library(
    name = "common_java_proto",
    deps = [":common_proto"],
    visibility = ["//visibility:public"]
)