proto_library(
    name = "agencyproto",
    srcs = ["agency.proto"]
)

java_proto_library(
    name = "java_agencyproto",
    deps = [":agencyproto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "calendarproto",
    srcs = ["calendar.proto"]
)

java_proto_library(
    name = "java_calendarproto",
    deps = [":calendarproto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "fareattributesproto",
    srcs = ["fare_attributes.proto"]
)

java_proto_library(
    name = "java_fareattributesproto",
    deps = [":fareattributesproto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "farerulesproto",
    srcs = ["fare_rules.proto"]
)

java_proto_library(
    name = "java_farerulesproto",
    deps = [":farerulesproto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "routesproto",
    srcs = ["routes.proto"]
)

java_proto_library(
    name = "java_routesproto",
    deps = [":routesproto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "shapesproto",
    srcs = ["shapes.proto"]
)

java_proto_library(
    name = "java_shapesproto",
    deps = [":shapesproto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "stoptimesproto",
    srcs = ["stop_times.proto"]
)

java_proto_library(
    name = "java_stoptimesproto",
    deps = [":stoptimesproto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "stopsproto",
    srcs = ["stops.proto"]
)

java_proto_library(
    name = "java_stopsproto",
    deps = [":stopsproto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "translationsproto",
    srcs = ["translations.proto"]
)

java_proto_library(
    name = "java_translationsproto",
    deps = [":translationsproto"],
    visibility = ["//visibility:public"]
)

proto_library(
    name = "tripsproto",
    srcs = ["trips.proto"]
)

java_proto_library(
    name = "java_tripsproto",
    deps = [":tripsproto"],
    visibility = ["//visibility:public"]
)