java_binary(
    name = "stackoverflow",
    srcs = ["DataExtractor.java",
        "ExtractedRow.java" ],
    main_class = "projects.stackoverflow.DataExtractor",
    visibility = ["//visibility:public"],
)
