package(default_visibility = ["//visibility:public"])

proto_library(
    name = "common_proto",
    srcs = ["RailWay.proto"],
)

java_proto_library(
    name = "railWay_proto",
    deps = [":common_proto"],
)
